### PR TITLE
Update ontology versions

### LINKED ISSUE #541: Update ontologies
- [x] Source: cl has a more recent version: 2024-02-13
- [x] Source: doid has a more recent version: 2024-01-31
- [x] Source: dron has a more recent version: 2024-02-20
- [x] Source: efo has a more recent version: 3.63.0
- [x] Source: go has a more recent version: 2024-01-17
- [x] Source: hp has a more recent version: 2024-02-08
- [x] Source: mondo has a more recent version: 2024-02-06
- [x] Source: mp has a more recent version: 2024-02-07
- [x] Source: ncbitaxon has a more recent version: 2023-12-12
- [x] Source: pw has a more recent version: 7.82
- [x] Source: uberon has a more recent version: 2024-02-20
- [x] Source: zp has a more recent version: 2024-01-22

### PR DESCRIPTION
**Pull request by Zethson**
Fixes https://github.com/laminlabs/bionty-base/issues/541

### CODE REVIEW

**Comment by sunnyosun** [comment]
I think the CI failing here is because you didn't upload any of the new ontology files to s3:
Screenshot 2024-03-13 at 12 40 35

**Comment by sunnyosun** [comment]
I made a guideline for the process here: https://github.com/laminlabs/bionty/issues/33

**Comment by sunnyosun** [comment]
Also could you make 10 PRs for this? Each PR should make a single update with a clear title.

Note that CellLine, NCBItaxon and ExperimentalFactor need manual curation (see guideline), so they also require a paired PR in [bionty-assets](https://github.com/laminlabs/bionty-assets).

**Comment by Zethson** [comment]
Yaa, I remember the `parquet` stuff but got distracted when the CI failed an I thought that it's due to the recent changes.

I'll do so!

**Pull request closed without merging**
