### PR TITLE
Add progressbar to downloads

### LINKED ISSUE #158: Download progress bars
Hey,

the status message when downloading a new ontology currently is

> ℹ️ Downloading reference for the first time might take a while...

Would it be possible to add download bars? I had no idea how large such an ontology is and how long the download would take. Of course, I also never know whether it's stuck or not.

I always implement them with https://rich.readthedocs.io/en/stable/progress.html

### PR DESCRIPTION
**Pull request by Zethson**
Hey,

this fixes #158 

* Adds a Rich progressbar to downloads
image
* Uses a more Pythonic way of checking whether the request is successful
* Adds some docstrings

The implementation is based on https://github.com/theislab/ehrapy/blob/development/ehrapy/data/_dataloader.py#L16
Alternatively, we could increase the complexity of this and follow the implementation of https://github.com/Textualize/rich/blob/e833da996e1b4468a53b15286fe831f59a2eaf11/examples/downloader.py#L40 . This would allow for multiple file downloads and concurrency but increase the code complexity. I don't see the need for this at the moment.

The download function is currently not covered by tests. We could either ignore it from codecov since it's standard code or eventually test the function with mocks?

I noticed that the metadata of several notebooks changed when running the tests. Should I revert this?

Signed-off-by: zethson <lukas.heumos@posteo.net>

### CODE REVIEW

**Comment by sunnyosun** [comment]
This looks great, @Zethson! Thank you for adding the progress bar!

**Comment by Zethson** [comment]
The build fails with:


```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/laminlabs/lndocs/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 13 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/laminlabs/lndocs/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 18 seconds before trying again
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/main*:refs/remotes/origin/main* +refs/tags/main*:refs/tags/main*
  remote: Repository not found.
  Error: fatal: repository 'https://github.com/laminlabs/lndocs/' not found
  Error: The process '/usr/bin/git' failed with exit code 128
```

Is the issue that I don't have access to the secret from my fork? https://github.com/laminlabs/bionty/blob/main/.github/workflows/build.yml#L26

**Comment by Zethson** [comment]
From the Github docs:

"Although workflows from forks do not have access to sensitive data such as secrets"

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks

**Comment by Zethson** [comment]
A possible solution:

(on the laminlabs organization level or on a per repository level)

1. Go to settings
2. Github Actions
3. General
4. Tick "Run workflows from fork pull requests "
5. Tick " Send secrets to workflows from fork pull requests. "

image

**Comment by sunnyosun** [comment]
This is all I see in settings, looks like everything is enabled already?

Screenshot 2023-01-02 at 12 17 27

**Comment by sunnyosun** [comment]
Hmm, this is all I saw in settings for actions:

Screenshot 2023-01-02 at 12 17 27

**Comment by Zethson** [comment]
@sunnyosun did you look at the repository settings or the organization settings? Do you have the same rights as @falexwolf ?

**Comment by Zethson** [comment]
But TBH, I'm not even sure whether this would solve the problem since this setting would only send repository secrets from private repositories. Your secret is likely an organization secret?

**Comment by falexwolf** [comment]
Thank you for this, @Zethson! 🙏

After the latest commit on main, it should now work for your fork if you rebase.

For the LaminDB, things are currently more tricky as there are several cloud-infra-related aspects to CI, which we can't safely get to work for forks. We'll need to go through branches in the main repo. I'll give you write access here & in LaminDB.

**Comment by Zethson** [comment]
@falexwolf Thanks!

@sunnyosun so two questions left:

1. codecov is failing aka decreasing because the download function isn't really covered by tests. If the download function were a part of a core laminlabs library and used by several packages I might investigate mocking this function. But as it is, I'd also be fine with a `# pragma no cover`. WDYT?
2. I noticed that the metadata of several notebooks changed when running the tests. Should I revert this?

Thanks!

**Comment by sunnyosun** [comment]
> @falexwolf Thanks!
> 
> @sunnyosun so two questions left:
> 
> 1. codecov is failing aka decreasing because the download function isn't really covered by tests. If the download function were a part of a core laminlabs library and used by several packages I might investigate mocking this function. But as it is, I'd also be fine with a `# pragma no cover`. WDYT?
> 2. I noticed that the metadata of several notebooks changed when running the tests. Should I revert this?
> 
> Thanks!

Hi @Zethson ,

1. I'm also fine with it not being covered now. We can always make efforts to increase the coverage at a later stage.
2. Yes, ideally if you could revert metadata changes and just commit the real edits in notebooks, that would be great!

Thank you!

**Review by sunnyosun — APPROVED** [review]
Looks great! Thank you! :)

**Pull request merged**
