### PR TITLE
Fix binaryio compatibility

### PR DESCRIPTION
**Pull request by Zethson**
Signed-off-by: zethson <lukas.heumos@posteo.net>

### CODE REVIEW

**Comment by Zethson** [comment]
@sunnyosun somehow the 3.7 and 3.8 CI still finds typing.binaryIO even though I deleted every occurrence of it in the code and the cache.

Am I missing something?

**Comment by sunnyosun** [comment]
> @sunnyosun somehow the 3.7 and 3.8 CI still finds typing.binaryIO even though I deleted every occurrence of it in the code and the cache.
> 
> Am I missing something?

Is it possible it's from https://pronto.readthedocs.io/en/stable/api/pronto.Ontology.html? Maybe Sphinx also searches for inherited classes?

**Comment by Zethson** [comment]
Yeah, I guess it's possible with intersphinx? This warning/error could be ignored at the sphinx level but meh. While I wouldn't mind disabling the 3.7 CI, I'd like to keep the 3.8 CI alive.

Not sure what the best course of action is

**Comment by sunnyosun** [comment]
Maybe let's just add this here for now? https://github.com/laminlabs/lndocs/blob/main/lndocs/lamin_sphinx/_nitpick_ignore.py

**Pull request closed without merging**
