### PR TITLE
Add current/lndb updating on new entities

### LINKED ISSUE #285: Upgrading Bionty to a version with new entities can result in access errors if the entitiy is missing in the _current.yaml
Need to find a way to verify that all by Bionty supported entities have a default in the `_current.yaml`. If this isn't the case, a reasonable default has to be added (top from `local.yaml`). We should not just regenerate the whole `_current.yaml`.

### PR DESCRIPTION
**Pull request by Zethson**
Fixes #285
Fixes a test for `update_defaults`. Now actually tests what it does, even though it wasn't completely wrong beforehand.

### CODE REVIEW

**Comment by Zethson** [comment]
I'd merge this into main and create a new release. This is fixing a major bug.

**Review by sunnyosun — COMMENTED** [review]
I'm not entirely sure about the ._lndb logic here, I think the lndb yaml shouldn't get new defaults from the versions.yaml, but rather from the instance?

**Comment by sunnyosun** [comment]
The .lndb logic is here: https://github.com/laminlabs/lndb/blob/main/lndb/dev/_setup_knowledge.py

- upon init, lamindb takes the .current.yaml to create versions table
- upon load, bionty writes .lndb.yaml from the instance

**Comment by sunnyosun** [comment]
So I think the update_defaults should only apply to .current.yaml, not to the .lndb.yaml, what do you think?

**Comment by Zethson** [comment]
Discussed on Slack

There are two cases that we need to distinguish:

1. We add a new Entity to Bionty -> IMO it's fine if we just append it to the .lndb.yaml -> it wasn't available beforehand so just take a default. This is what this PR covers.
2. Someone adds a new Entity to Bionty on their own with lamin -> this needs to be fetched and then added like you explained it. We don't cover this case yet.

**Pull request merged**
